name: Build and Publish
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build Web Application
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - uses: actions/checkout@v3
      - name: build pipeline
        run: go run dagger/main.go -pipeline=Build
      - name: archive
        uses: actions/upload-artifact@v1
        with:
          name: web-app
          path: dist
  publish:
    name: Publish Web Artifacts
    if: contains(github.ref, 'main')
    environment: production
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: retrive archive
        uses: actions/download-artifact@v1
        with:
          name: web-app
          path: dist
      - name: initialize Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - name: publish to production S3
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESSS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          pip install pipenv
          cd $GITHUB_WORKSPACE
          pipenv install
          pipenv run ansible-playbook ansible/playbook.yml
