name: Build and Publish
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build Web Application
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout out repository
        uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: initialize
        run: npm install
      - name: test
        run: npm run build
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test
      - name: clean dist directory
        if: contains(github.ref, 'main')
        run: rm -rf dist/
      - name: build
        if: contains(github.ref, 'main')
        run: npm run build:prod
      - name: archive
        uses: actions/upload-artifact@v1
        with:
          name: web-app
          path: dist
  publish:
    name: Publish web artifacts
    if: contains(github.ref, 'main')
    environment: production
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: retrive archive
        uses: actions/download-artifact@v1
        with:
          name: web-app
          path: dist
      - name: initialize python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - name: run deployment playbook
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESSS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          pip install pipenv
          cd $GITHUB_WORKSPACE
          pipenv install
          pipenv run ansible-playbook ansible/playbook.yml
