name: Build and Publish
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build Web Application
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: initialize Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - name: npm initialize
        run: npm ci
      - name: build
        run: npm run build --if-present
      - name: lint
        run: npm run lint
      - name: test
        run: npm test
      - name: archive
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: web-app
          path: dist/web
  publish:
    name: Publish Web Artifacts
    if: contains(github.ref, 'main')
    environment: production
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: retrive archive
        uses: actions/download-artifact@v4
        with:
          name: web-app
          path: dist/web
      - name: deploy to firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PERSONAL_APP_395017 }}'
          channelId: live
          projectId: personal-app-395017
