name: Pull Request Publish
on:
  pull_request_review:
    types: [submitted]

jobs:
  publish:
    if: github.event.review.state == 'approved'
    name: Publish to GitHub Pages
    runs-on: ubuntu-20.04
    environment: development
    steps:
      - name: Checkout out
        uses: actions/checkout@v3
      - name: initialize Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: actions/checkout@v3
      - name: initialize dependencies
        run: npm install
      - name: deploy to github pages
        run: node --loader ts-node/esm ./build.mts --pipeline deployGitHubPages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: deploy to firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PERSONAL_APP_395017 }}'
          projectId: personal-app-395017
