name: Pull Request Publish
on:
  pull_request_review:
    types: [submitted]

jobs:
  publish:
    if: github.event.review.state == 'approved'
    name: Publish to GitHub Pages
    runs-on: ubuntu-20.04
    environment: development
    steps:
      - name: Checkout out
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - uses: actions/checkout@v3
      - name: build pipeline
        run: go run dagger/main.go -pipeline=DeployGitHubPages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
