name: Pull Request Publish
on:
  pull_request_review:
    types: [submitted]

jobs:
  publish:
    if: github.event.review.state == 'approved'
    name: Publish to GitHub Pages
    runs-on: ubuntu-20.04
    environment: development
    steps:
      - name: Checkout out repository
        uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: initialize
        run: npm install
      - name: build
        run: npm run build
      - name: deploy to github pages
        run: npm run deploy:github -- --name=jolt23 --email=github-actions@github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
